// flow-typed signature: dc377e5cfd6d1981c4a0ec6c503a7d8b
// flow-typed version: <<STUB>>/react-easy-transition_v^1.2.4/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-easy-transition'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-easy-transition' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-easy-transition/lib/ReactEasyTransition' {
  declare module.exports: any;
}

declare module 'react-easy-transition/lib/TransitionChild' {
  declare module.exports: any;
}

declare module 'react-easy-transition/src/ReactEasyTransition' {
  declare module.exports: any;
}

declare module 'react-easy-transition/src/TransitionChild' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-easy-transition/lib/ReactEasyTransition.js' {
  declare module.exports: $Exports<'react-easy-transition/lib/ReactEasyTransition'>;
}
declare module 'react-easy-transition/lib/TransitionChild.js' {
  declare module.exports: $Exports<'react-easy-transition/lib/TransitionChild'>;
}
declare module 'react-easy-transition/src/ReactEasyTransition.js' {
  declare module.exports: $Exports<'react-easy-transition/src/ReactEasyTransition'>;
}
declare module 'react-easy-transition/src/TransitionChild.js' {
  declare module.exports: $Exports<'react-easy-transition/src/TransitionChild'>;
}
